<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Categoria_prod_serv extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Categoria_prod_serv_model');
    }

    /*
     * Listing of categoria_prod_servs
     */
    function index()
    {
        $data['categoria_prod_servs'] = $this->Categoria_prod_serv_model->get_all_categoria_prod_servs();

      //  $data['_view'] = 'categoria_prod_serv/index';
      //  $this->load->view('layouts/main',$data);

        $this->load->view('include/header');
        $this->load->view('categoria_prod_serv/index',$data);
        $this->load->view('include/footer');
    }

    /*
     * Adding a new categoria_prod_serv
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nome','Nome','required');

		if($this->form_validation->run())
        {
            $params = array(
				'status' => $this->input->post('status'),
				'nome' => $this->input->post('nome'),
            );

            $categoria_prod_serv_id = $this->Categoria_prod_serv_model->add_categoria_prod_serv($params);
            redirect('categoria_prod_serv/index');
        }
        else
        {
          //  $data['_view'] = 'categoria_prod_serv/add';
        //    $this->load->view('layouts/main',$data);

        $this->load->view('include/header');
        $this->load->view('categoria_prod_serv/add');
        $this->load->view('include/footer');
        }
    }

    /*
     * Editing a categoria_prod_serv
     */
    function edit($idcategoria_prod_serv)
    {
        // check if the categoria_prod_serv exists before trying to edit it
        $data['categoria_prod_serv'] = $this->Categoria_prod_serv_model->get_categoria_prod_serv($idcategoria_prod_serv);

        if(isset($data['categoria_prod_serv']['idcategoria_prod_serv']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nome','Nome','required');

			if($this->form_validation->run())
            {
                $params = array(
					'status' => $this->input->post('status'),
					'nome' => $this->input->post('nome'),
                );

                $this->Categoria_prod_serv_model->update_categoria_prod_serv($idcategoria_prod_serv,$params);
                redirect('categoria_prod_serv/index');
            }
            else
            {
              //  $data['_view'] = 'categoria_prod_serv/edit';
            //    $this->load->view('layouts/main',$data);

            $this->load->view('include/header');
            $this->load->view('categoria_prod_serv/edit',$data);
            $this->load->view('include/footer');
            }
        }
        else
            show_error('The categoria_prod_serv you are trying to edit does not exist.');
    }

    /*
     * Deleting categoria_prod_serv
     */
    function remove($idcategoria_prod_serv)
    {
        $categoria_prod_serv = $this->Categoria_prod_serv_model->get_categoria_prod_serv($idcategoria_prod_serv);

        // check if the categoria_prod_serv exists before trying to delete it
        if(isset($categoria_prod_serv['idcategoria_prod_serv']))
        {
            $this->Categoria_prod_serv_model->delete_categoria_prod_serv($idcategoria_prod_serv);
            redirect('categoria_prod_serv/index');
        }
        else
            show_error('The categoria_prod_serv you are trying to delete does not exist.');
    }

}
