<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Contasareceber extends CI_Controller{
    function __construct()
    {
        parent::__construct();

        if( (!session_id()) || (!$this->session->userdata('logado'))){
            redirect('dashboard/index');
}
        $this->load->model('Contasareceber_model');
    }

    /*
     * Listing of contasarecebers
     */
    function index()
    {
        $data['contasarecebers'] = $this->Contasareceber_model->get_all_contasarecebers();

      //  $data['_view'] = 'contasareceber/index';
    //    $this->load->view('layouts/main',$data);

    $this->load->view('include/header');
    $this->load->view('contasareceber/index',$data);
    $this->load->view('include/footer');
    }

    /*
     * Adding a new contasareceber
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('descricao','Descricao','required');
		$this->form_validation->set_rules('valor','Valor','required');
		$this->form_validation->set_rules('datavencimento','Datavencimento','required');

		if($this->form_validation->run())
        {
            $params = array(
				'formarecebimento' => $this->input->post('formarecebimento'),
				'descricao' => $this->input->post('descricao'),
				'numero' => $this->input->post('numero'),
				'valor' => $this->input->post('valor'),
				'datavencimento' => $this->input->post('datavencimento'),
				'datapagamento' => $this->input->post('datapagamento'),
				'obs' => $this->input->post('obs'),
            );

            $contasareceber_id = $this->Contasareceber_model->add_contasareceber($params);
            redirect('contasareceber/index');
        }
        else
        {
			$this->load->model('Formarecebimento_model');
			$data['all_formarecebimentos'] = $this->Formarecebimento_model->get_all_formarecebimentos();

          //  $data['_view'] = 'contasareceber/add';
          //  $this->load->view('layouts/main',$data);

          $this->load->view('include/header');
          $this->load->view('contasareceber/add',$data);
          $this->load->view('include/footer');
        }
    }

    function faturavenda()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('descricao','Descricao','required');
		$this->form_validation->set_rules('valor','Valor','required');
		$this->form_validation->set_rules('datavencimento','Datavencimento','required');


    if($this->input->post('datapagamento')!=NULL){
        $statusfechado = 2;

        $idag =  $this->input->post('idagendamento');
        $itemstatus = $this->input->post('itemstatus');
    

$this->load->model('Calendar_model');
$si =  $this->Calendar_model->update_serv($idag,$itemstatus);
        $dd =  $this->Calendar_model->update_status($idag,$statusfechado);



$tipomovi = 1;
        $fluxo = array(

            'forma' => $this->input->post('formarecebimento'),
          'data' => $this->input->post('datapagamento'),
          'valor' => $this->input->post('valor'),
            'descricao' => $this->input->post('descricao'),
          'tipomov' =>$tipomovi,
        );

        $this->load->model('Fluxo_model');

          $d =  $this->Fluxo_model->add($fluxo);
    }

		if($this->form_validation->run())
        {
            $params = array(
				'formarecebimento' => $this->input->post('formarecebimento'),
				'descricao' => $this->input->post('descricao'),
				'numero' => $this->input->post('numero'),
				'valor' => $this->input->post('valor'),
				'datavencimento' => $this->input->post('datavencimento'),
				'datapagamento' => $this->input->post('datapagamento'),
				'obs' => $this->input->post('obs'),
            );

            $contasareceber_id = $this->Contasareceber_model->add_contasareceber($params);
            redirect('contasareceber/index');
        }
        else
        {
			$this->load->model('Formarecebimento_model');
			$data['all_formarecebimentos'] = $this->Formarecebimento_model->get_all_formarecebimentos();

          //  $data['_view'] = 'contasareceber/add';
          //  $this->load->view('layouts/main',$data);

          $this->load->view('include/header');
          $this->load->view('contasareceber/add',$data);
          $this->load->view('include/footer');
        }
    }

    /*
     * Editing a contasareceber
     */
    function edit($idcontasareceber)
    {
        // check if the contasareceber exists before trying to edit it
        $data['contasareceber'] = $this->Contasareceber_model->get_contasareceber($idcontasareceber);

        if(isset($data['contasareceber']['idcontasareceber']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('descricao','Descricao','required');
			$this->form_validation->set_rules('valor','Valor','required');
			$this->form_validation->set_rules('datavencimento','Datavencimento','required');

      if($this->input->post('datapagamento')!=NULL){




  $tipomovi = 1;
          $fluxo = array(

              'forma' => $this->input->post('formarecebimento'),
            'data' => $this->input->post('datapagamento'),
            'valor' => $this->input->post('valor'),
              'descricao' => $this->input->post('descricao'),
            'tipomov' =>$tipomovi,
          );

          $this->load->model('Fluxo_model');

            $d =  $this->Fluxo_model->add($fluxo);
      }

			if($this->form_validation->run())
            {
                $params = array(
					'formarecebimento' => $this->input->post('formarecebimento'),
					'descricao' => $this->input->post('descricao'),
					'numero' => $this->input->post('numero'),
					'valor' => $this->input->post('valor'),
					'datavencimento' => $this->input->post('datavencimento'),
					'datapagamento' => $this->input->post('datapagamento'),
					'obs' => $this->input->post('obs'),
                );

                $this->Contasareceber_model->update_contasareceber($idcontasareceber,$params);
                redirect('contasareceber/index');
            }
            else
            {
				$this->load->model('Formarecebimento_model');
				$data['all_formarecebimentos'] = $this->Formarecebimento_model->get_all_formarecebimentos();

            //    $data['_view'] = 'contasareceber/edit';
              //  $this->load->view('layouts/main',$data);

              $this->load->view('include/header');
              $this->load->view('contasareceber/edit',$data);
              $this->load->view('include/footer');
            }
        }
        else
            show_error('The contasareceber you are trying to edit does not exist.');
    }

    /*
     * Deleting contasareceber
     */
    function remove($idcontasareceber)
    {
        $contasareceber = $this->Contasareceber_model->get_contasareceber($idcontasareceber);

        // check if the contasareceber exists before trying to delete it
        if(isset($contasareceber['idcontasareceber']))
        {
            $this->Contasareceber_model->delete_contasareceber($idcontasareceber);
            redirect('contasareceber/index');
        }
        else
            show_error('The contasareceber you are trying to delete does not exist.');
    }

}
