<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Fluxo extends CI_Controller{
    function __construct()
    {
        parent::__construct();

        if( (!session_id()) || (!$this->session->userdata('logado'))){
            redirect('dashboard/index');
}


        $this->load->model('Fluxo_model');
    }

    function fluxo(){

      $this->load->model('Fluxo_model');
$data['result'] = 0;
      $this->load->view('include/header');
      $this->load->view('fluxo/fluxocaixa',$data);
      $this->load->view('include/footer');
    }

    function buscafluxo(){

      $inicio = $this->input->post('data');

      $data['result'] = $this->Fluxo_model->getfluxo($inicio);

      $this->load->view('include/header');
      $this->load->view('fluxo/fluxocaixa',$data);
      $this->load->view('include/footer');
    }

  }
