<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Item_agenda extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Item_agenda_model');
    } 

    /*
     * Listing of item_agendas
     */
    function index()
    {
        $data['item_agendas'] = $this->Item_agenda_model->get_all_item_agendas();
        
        $data['_view'] = 'item_agenda/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new item_agenda
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idagenda' => $this->input->post('idagenda'),
				'horaagenda' => $this->input->post('horaagenda'),
				'dataagenda' => $this->input->post('dataagenda'),
				'idservico' => $this->input->post('idservico'),
				'idatendente' => $this->input->post('idatendente'),
				'valorservico' => $this->input->post('valorservico'),
				'dataexecucao' => $this->input->post('dataexecucao'),
				'status' => $this->input->post('status'),
            );
            
            $item_agenda_id = $this->Item_agenda_model->add_item_agenda($params);
            redirect('item_agenda/index');
        }
        else
        {
			$this->load->model('Agenda_model');
			$data['all_agendas'] = $this->Agenda_model->get_all_agendas();
            
            $data['_view'] = 'item_agenda/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a item_agenda
     */
    function edit($iditem_agenda)
    {   
        // check if the item_agenda exists before trying to edit it
        $data['item_agenda'] = $this->Item_agenda_model->get_item_agenda($iditem_agenda);
        
        if(isset($data['item_agenda']['iditem_agenda']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idagenda' => $this->input->post('idagenda'),
					'horaagenda' => $this->input->post('horaagenda'),
					'dataagenda' => $this->input->post('dataagenda'),
					'idservico' => $this->input->post('idservico'),
					'idatendente' => $this->input->post('idatendente'),
					'valorservico' => $this->input->post('valorservico'),
					'dataexecucao' => $this->input->post('dataexecucao'),
					'status' => $this->input->post('status'),
                );

                $this->Item_agenda_model->update_item_agenda($iditem_agenda,$params);            
                redirect('item_agenda/index');
            }
            else
            {
				$this->load->model('Agenda_model');
				$data['all_agendas'] = $this->Agenda_model->get_all_agendas();

                $data['_view'] = 'item_agenda/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The item_agenda you are trying to edit does not exist.');
    } 

    /*
     * Deleting item_agenda
     */
    function remove($iditem_agenda)
    {
        $item_agenda = $this->Item_agenda_model->get_item_agenda($iditem_agenda);

        // check if the item_agenda exists before trying to delete it
        if(isset($item_agenda['iditem_agenda']))
        {
            $this->Item_agenda_model->delete_item_agenda($iditem_agenda);
            redirect('item_agenda/index');
        }
        else
            show_error('The item_agenda you are trying to delete does not exist.');
    }
    
}
