<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Item_serv extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Item_serv_model');
    } 

    /*
     * Listing of item_servs
     */
    function index()
    {
        $data['item_servs'] = $this->Item_serv_model->get_all_item_servs();
        
        $data['_view'] = 'item_serv/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new item_serv
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('comissao','Comissao','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idserv' => $this->input->post('idserv'),
				'nomeserv' => $this->input->post('nomeserv'),
				'idpacote' => $this->input->post('idpacote'),
				'comissao' => $this->input->post('comissao'),
            );
            
            $item_serv_id = $this->Item_serv_model->add_item_serv($params);
            redirect('item_serv/index');
        }
        else
        {
			$this->load->model('Servico_model');
			$data['all_servicos'] = $this->Servico_model->get_all_servicos();
            
            $data['_view'] = 'item_serv/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a item_serv
     */
    function edit($iditem_serv)
    {   
        // check if the item_serv exists before trying to edit it
        $data['item_serv'] = $this->Item_serv_model->get_item_serv($iditem_serv);
        
        if(isset($data['item_serv']['iditem_serv']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('comissao','Comissao','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'idserv' => $this->input->post('idserv'),
					'nomeserv' => $this->input->post('nomeserv'),
					'idpacote' => $this->input->post('idpacote'),
					'comissao' => $this->input->post('comissao'),
                );

                $this->Item_serv_model->update_item_serv($iditem_serv,$params);            
                redirect('item_serv/index');
            }
            else
            {
				$this->load->model('Servico_model');
				$data['all_servicos'] = $this->Servico_model->get_all_servicos();

                $data['_view'] = 'item_serv/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The item_serv you are trying to edit does not exist.');
    } 

    /*
     * Deleting item_serv
     */
    function remove($iditem_serv)
    {
        $item_serv = $this->Item_serv_model->get_item_serv($iditem_serv);

        // check if the item_serv exists before trying to delete it
        if(isset($item_serv['iditem_serv']))
        {
            $this->Item_serv_model->delete_item_serv($iditem_serv);
            redirect('item_serv/index');
        }
        else
            show_error('The item_serv you are trying to delete does not exist.');
    }
    
}
