<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Servcliente extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Servcliente_model');
    } 

    /*
     * Listing of servcliente
     */
    function index()
    {
        $data['servcliente'] = $this->Servcliente_model->get_all_servcliente();
        
        $data['_view'] = 'servcliente/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new servcliente
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idcliente' => $this->input->post('idcliente'),
				'idagenda' => $this->input->post('idagenda'),
				'idservico' => $this->input->post('idservico'),
				'dataagenda' => $this->input->post('dataagenda'),
				'dataexecucao' => $this->input->post('dataexecucao'),
            );
            
            $servcliente_id = $this->Servcliente_model->add_servcliente($params);
            redirect('servcliente/index');
        }
        else
        {            
            $data['_view'] = 'servcliente/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a servcliente
     */
    function edit($idservcliente)
    {   
        // check if the servcliente exists before trying to edit it
        $data['servcliente'] = $this->Servcliente_model->get_servcliente($idservcliente);
        
        if(isset($data['servcliente']['idservcliente']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idcliente' => $this->input->post('idcliente'),
					'idagenda' => $this->input->post('idagenda'),
					'idservico' => $this->input->post('idservico'),
					'dataagenda' => $this->input->post('dataagenda'),
					'dataexecucao' => $this->input->post('dataexecucao'),
                );

                $this->Servcliente_model->update_servcliente($idservcliente,$params);            
                redirect('servcliente/index');
            }
            else
            {
                $data['_view'] = 'servcliente/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The servcliente you are trying to edit does not exist.');
    } 

    /*
     * Deleting servcliente
     */
    function remove($idservcliente)
    {
        $servcliente = $this->Servcliente_model->get_servcliente($idservcliente);

        // check if the servcliente exists before trying to delete it
        if(isset($servcliente['idservcliente']))
        {
            $this->Servcliente_model->delete_servcliente($idservcliente);
            redirect('servcliente/index');
        }
        else
            show_error('The servcliente you are trying to delete does not exist.');
    }
    
}
