<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Servico extends CI_Controller{
    function __construct()
    {
        parent::__construct();

        if( (!session_id()) || (!$this->session->userdata('logado'))){
            redirect('dashboard/index');
}
        $this->load->model('Servico_model');
    }

    /*
     * Listing of servicos
     */
    function index()
    {
        $data['servicos'] = $this->Servico_model->get_all_servicos();

      //  $data['_view'] = 'servico/index';
    //    $this->load->view('layouts/main',$data);

      $this->load->view('include/header');
      $this->load->view('servico/index',$data);
      $this->load->view('include/footer');
    }

    /*
     * Adding a new servico
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nomeservico','Nome do serviço','required');
		$this->form_validation->set_rules('valorserv','Valor de venda','required');
		$this->form_validation->set_rules('idcategoria','categoria','required');

		if($this->form_validation->run())
        {
            $params = array(
				'idcategoria' => $this->input->post('idcategoria'),
				'nomeservico' => $this->input->post('nomeservico'),
				'valorserv' => $this->input->post('valorserv'),
				'status' => $this->input->post('status'),
				'comissao' => $this->input->post('comissao'),
				'tiposervico' => $this->input->post('tiposervico'),
            );

            $servico_id = $this->Servico_model->add_servico($params);
            redirect('servico/index');
        }
        else
        {
			$this->load->model('Categoria_prod_serv_model');
			$data['all_categoria_prod_servs'] = $this->Categoria_prod_serv_model->get_all_categoria_prod_servs();

        //    $data['_view'] = 'servico/add';
        //    $this->load->view('layouts/main',$data);

        $this->load->view('include/header');
        $this->load->view('servico/add',$data);
        $this->load->view('include/footer');
        }
    }

    function addpacote(){

      $params = array(
  'nomeservico' => $this->input->post('pacotenome'),
  'valorserv' => $this->input->post('valorpacote'),
  'tiposervico' => $this->input->post('tiposerv'),
  'status' => $this->input->post('statuspacote')


  		);

  		  $pacote = $this->Servico_model->addpacote($params);

        $count = count($this->input->post('comissao'));
        for($i=0; $i< $count;$i++){
        	$itens = array(

        			'idpacote' => $pacote,
        			'nomeserv' =>  $this->input->post('item')[$i],

              'comissao' => $this->input->post('comissao')[$i]



        	);

        		$itens = $this->Servico_model->itempacote($itens);


        }


         redirect(base_url('servico'));


    }

    /*
     * Editing a servico
     */
    function edit($idservico)
    {
        // check if the servico exists before trying to edit it
        $data['servico'] = $this->Servico_model->get_servico($idservico);

        if(isset($data['servico']['idservico']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nomeservico','Nome do serviço','required');
			$this->form_validation->set_rules('valorserv','Valor ','required');
			$this->form_validation->set_rules('idcategoria','Categoria','required');

			if($this->form_validation->run())
            {
                $params = array(
					'idcategoria' => $this->input->post('idcategoria'),
					'nomeservico' => $this->input->post('nomeservico'),
					'valorserv' => $this->input->post('valorserv'),
					'status' => $this->input->post('status'),
					'comissao' => $this->input->post('comissao'),
					'tiposervico' => $this->input->post('tiposervico'),
                );

                $this->Servico_model->update_servico($idservico,$params);
                redirect('servico/index');
            }
            else
            {
				$this->load->model('Categoria_prod_serv_model');
				$data['all_categoria_prod_servs'] = $this->Categoria_prod_serv_model->get_all_categoria_prod_servs();

            //    $data['_view'] = 'servico/edit';
              //  $this->load->view('layouts/main',$data);

              $this->load->view('include/header');
              $this->load->view('servico/edit',$data);
              $this->load->view('include/footer');
            }
        }
        else
            show_error('The servico you are trying to edit does not exist.');
    }

    /*
     * Deleting servico
     */
    function remove($idservico)
    {
        $servico = $this->Servico_model->get_servico($idservico);

        // check if the servico exists before trying to delete it
        if(isset($servico['idservico']))
        {
            $this->Servico_model->delete_servico($idservico);
            redirect('servico/index');
        }
        else
            show_error('The servico you are trying to delete does not exist.');
    }

}
