<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Agenda_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get agenda by idagenda
     */
    function get_agenda($idagenda)
    {
        return $this->db->get_where('agenda',array('idagenda'=>$idagenda))->row_array();
    }
    public function listausuariosagenda(){

      $sql = "SELECT * from atendente";
           $query = $this->db->query($sql);
           $array = $query->result_array();
           return $array;
    }
    /*
     * Get all agendas
     */
    function get_all_agendas()
    {
        $this->db->order_by('idagenda', 'desc');
        return $this->db->get('agenda')->result_array();
    }

    /*
     * function to add new agenda
     */
    function add_agenda($params)
    {
        $this->db->insert('agenda',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update agenda
     */
    function update_agenda($idagenda,$params)
    {
        $this->db->where('idagenda',$idagenda);
        return $this->db->update('agenda',$params);
    }

    /*
     * function to delete agenda
     */
    function delete_agenda($idagenda)
    {
        return $this->db->delete('agenda',array('idagenda'=>$idagenda));
    }
}
