<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Atendente_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get atendente by idatendente
     */
    function get_atendente($idatendente)
    {
        return $this->db->get_where('atendente',array('idatendente'=>$idatendente))->row_array();
    }

  
    /*
     * Get all atendentes
     */
    function get_all_atendentes()
    {
        $this->db->order_by('idatendente', 'desc');
        return $this->db->get('atendente')->result_array();
    }

    /*
     * function to add new atendente
     */
    function add_atendente($params)
    {
        $this->db->insert('atendente',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update atendente
     */
    function update_atendente($idatendente,$params)
    {
        $this->db->where('idatendente',$idatendente);
        return $this->db->update('atendente',$params);
    }

    /*
     * function to delete atendente
     */
    function delete_atendente($idatendente)
    {
        return $this->db->delete('atendente',array('idatendente'=>$idatendente));
    }
}
