<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categoria_prod_serv_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categoria_prod_serv by idcategoria_prod_serv
     */
    function get_categoria_prod_serv($idcategoria_prod_serv)
    {
        return $this->db->get_where('categoria_prod_serv',array('idcategoria_prod_serv'=>$idcategoria_prod_serv))->row_array();
    }
        
    /*
     * Get all categoria_prod_servs
     */
    function get_all_categoria_prod_servs()
    {
        $this->db->order_by('idcategoria_prod_serv', 'desc');
        return $this->db->get('categoria_prod_serv')->result_array();
    }
        
    /*
     * function to add new categoria_prod_serv
     */
    function add_categoria_prod_serv($params)
    {
        $this->db->insert('categoria_prod_serv',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update categoria_prod_serv
     */
    function update_categoria_prod_serv($idcategoria_prod_serv,$params)
    {
        $this->db->where('idcategoria_prod_serv',$idcategoria_prod_serv);
        return $this->db->update('categoria_prod_serv',$params);
    }
    
    /*
     * function to delete categoria_prod_serv
     */
    function delete_categoria_prod_serv($idcategoria_prod_serv)
    {
        return $this->db->delete('categoria_prod_serv',array('idcategoria_prod_serv'=>$idcategoria_prod_serv));
    }
}
