<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Contasareceber_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get contasareceber by idcontasareceber
     */
    function get_contasareceber($idcontasareceber)
    {
        return $this->db->get_where('contasareceber',array('idcontasareceber'=>$idcontasareceber))->row_array();
    }

    /*
     * Get all contasarecebers
     */
    function get_all_contasarecebers()
    {
        $this->db->order_by('idcontasareceber', 'desc');
        return $this->db->get('contasareceber')->result_array();
    }

    public function get_current_page_records($limit, $start)
        {

    				$this->db->order_by('idcontasareceber','desc');
            $this->db->limit($limit, $start);

            $query = $this->db->get("contasareceber");

            if ($query->num_rows() > 0)
            {
                foreach ($query->result() as $row)
                {
                    $data[] = $row;
                }

                return $data;
            }

            return false;
        }

    /*
     * function to add new contasareceber
     */

     public function get_total() {

     		return $this->db->count_all("contasareceber");
     }
    function add_contasareceber($params)
    {
        $this->db->insert('contasareceber',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update contasareceber
     */
    function update_contasareceber($idcontasareceber,$params)
    {
        $this->db->where('idcontasareceber',$idcontasareceber);
        return $this->db->update('contasareceber',$params);
    }




    /*
     * function to delete contasareceber
     */
    function delete_contasareceber($idcontasareceber)
    {
        return $this->db->delete('contasareceber',array('idcontasareceber'=>$idcontasareceber));
    }
}
