<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Contasareceber_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get contasareceber by idcontasareceber
     */
    function get_contasareceber($idcontasareceber)
    {
        return $this->db->get_where('contasareceber',array('idcontasareceber'=>$idcontasareceber))->row_array();
    }

    /*
     * Get all contasarecebers
     */
    function get_all_contasarecebers()
    {
        $this->db->order_by('idcontasareceber', 'desc');
        return $this->db->get('contasareceber')->result_array();
    }

    /*
     * function to add new contasareceber
     */
    function add_contasareceber($params)
    {
        $this->db->insert('contasareceber',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update contasareceber
     */
    function update_contasareceber($idcontasareceber,$params)
    {
        $this->db->where('idcontasareceber',$idcontasareceber);
        return $this->db->update('contasareceber',$params);
    }


  

    /*
     * function to delete contasareceber
     */
    function delete_contasareceber($idcontasareceber)
    {
        return $this->db->delete('contasareceber',array('idcontasareceber'=>$idcontasareceber));
    }
}
