<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Formarecebimento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get formarecebimento by idformarecebimento
     */
    function get_formarecebimento($idformarecebimento)
    {
        return $this->db->get_where('formarecebimento',array('idformarecebimento'=>$idformarecebimento))->row_array();
    }
        
    /*
     * Get all formarecebimentos
     */
    function get_all_formarecebimentos()
    {
        $this->db->order_by('idformarecebimento', 'desc');
        return $this->db->get('formarecebimento')->result_array();
    }
        
    /*
     * function to add new formarecebimento
     */
    function add_formarecebimento($params)
    {
        $this->db->insert('formarecebimento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update formarecebimento
     */
    function update_formarecebimento($idformarecebimento,$params)
    {
        $this->db->where('idformarecebimento',$idformarecebimento);
        return $this->db->update('formarecebimento',$params);
    }
    
    /*
     * function to delete formarecebimento
     */
    function delete_formarecebimento($idformarecebimento)
    {
        return $this->db->delete('formarecebimento',array('idformarecebimento'=>$idformarecebimento));
    }
}
