<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Item_agenda_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get item_agenda by iditem_agenda
     */
    function get_item_agenda($iditem_agenda)
    {
        return $this->db->get_where('item_agenda',array('iditem_agenda'=>$iditem_agenda))->row_array();
    }
        
    /*
     * Get all item_agendas
     */
    function get_all_item_agendas()
    {
        $this->db->order_by('iditem_agenda', 'desc');
        return $this->db->get('item_agenda')->result_array();
    }
        
    /*
     * function to add new item_agenda
     */
    function add_item_agenda($params)
    {
        $this->db->insert('item_agenda',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update item_agenda
     */
    function update_item_agenda($iditem_agenda,$params)
    {
        $this->db->where('iditem_agenda',$iditem_agenda);
        return $this->db->update('item_agenda',$params);
    }
    
    /*
     * function to delete item_agenda
     */
    function delete_item_agenda($iditem_agenda)
    {
        return $this->db->delete('item_agenda',array('iditem_agenda'=>$iditem_agenda));
    }
}
