<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Item_serv_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get item_serv by iditem_serv
     */
    function get_item_serv($iditem_serv)
    {
        return $this->db->get_where('item_serv',array('iditem_serv'=>$iditem_serv))->row_array();
    }
        
    /*
     * Get all item_servs
     */
    function get_all_item_servs()
    {
        $this->db->order_by('iditem_serv', 'desc');
        return $this->db->get('item_serv')->result_array();
    }
        
    /*
     * function to add new item_serv
     */
    function add_item_serv($params)
    {
        $this->db->insert('item_serv',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update item_serv
     */
    function update_item_serv($iditem_serv,$params)
    {
        $this->db->where('iditem_serv',$iditem_serv);
        return $this->db->update('item_serv',$params);
    }
    
    /*
     * function to delete item_serv
     */
    function delete_item_serv($iditem_serv)
    {
        return $this->db->delete('item_serv',array('iditem_serv'=>$iditem_serv));
    }
}
