<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Produto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get produto by idproduto
     */
    function get_produto($idproduto)
    {
        return $this->db->get_where('produto',array('idproduto'=>$idproduto))->row_array();
    }
        
    /*
     * Get all produtos
     */
    function get_all_produtos()
    {
        $this->db->order_by('idproduto', 'desc');
        return $this->db->get('produto')->result_array();
    }
        
    /*
     * function to add new produto
     */
    function add_produto($params)
    {
        $this->db->insert('produto',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update produto
     */
    function update_produto($idproduto,$params)
    {
        $this->db->where('idproduto',$idproduto);
        return $this->db->update('produto',$params);
    }
    
    /*
     * function to delete produto
     */
    function delete_produto($idproduto)
    {
        return $this->db->delete('produto',array('idproduto'=>$idproduto));
    }
}
