<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Servcliente_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get servcliente by idservcliente
     */
    function get_servcliente($idservcliente)
    {
        return $this->db->get_where('servcliente',array('idservcliente'=>$idservcliente))->row_array();
    }
        
    /*
     * Get all servcliente
     */
    function get_all_servcliente()
    {
        $this->db->order_by('idservcliente', 'desc');
        return $this->db->get('servcliente')->result_array();
    }
        
    /*
     * function to add new servcliente
     */
    function add_servcliente($params)
    {
        $this->db->insert('servcliente',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update servcliente
     */
    function update_servcliente($idservcliente,$params)
    {
        $this->db->where('idservcliente',$idservcliente);
        return $this->db->update('servcliente',$params);
    }
    
    /*
     * function to delete servcliente
     */
    function delete_servcliente($idservcliente)
    {
        return $this->db->delete('servcliente',array('idservcliente'=>$idservcliente));
    }
}
